const TARGETS={sd:{label:'SD Swasta',usia:6,lama:6},smp:{label:'SMP Swasta',usia:12,lama:3},sma:{label:'SMA Swasta',usia:15,lama:3},s1dn:{label:'S1 Dalam Negeri',usia:18,lama:4},s1ln:{label:'S1 Luar Negeri',usia:18,lama:4},kedokteran:{label:'Kedokteran',usia:18,lama:6},s2dn:{label:'S2 Dalam Negeri',usia:22,lama:2},s2ln:{label:'S2 Luar Negeri',usia:22,lama:2},custom:{label:'Custom',usia:'',lama:''}};
const FP={whatsapp:'628116946999',phone:'0811-6946-999',email:'septinogao@gmail.com',instagram:'https://instagram.com/septino.gao',ig:'@septino.gao',name:'Septino, QWP®, CIS®',title:'Financial Planner & Insurance Consultant'};
let last=null;let donutChart=null;

document.addEventListener('DOMContentLoaded',()=>{tahunSekarang.value=new Date().getFullYear();applyTarget();bindEvents();updatePeriode();kosongkan();window.exportPDF=exportPDF;window.hitung=hitung;window.resetForm=resetForm;});
function bindEvents(){allInputs().forEach(el=>el.addEventListener('input',()=>{formatIfMoney(el);updatePeriode();hitung(false);}));targetPendidikan.addEventListener('change',()=>{applyTarget();updatePeriode();hitung(false);});periodePersiapan.addEventListener('change',()=>{customTahunBox.classList.toggle('d-none',periodePersiapan.value!=='custom');hitung(false);});document.querySelectorAll('input[name="strategiInvestasi"]').forEach(r=>r.addEventListener('change',()=>hitung(false)));btnExportPDF.addEventListener('click',exportPDF);}
function allInputs(){return [...document.querySelectorAll('#simulasiForm input,#simulasiForm select,#simulasiForm textarea')];}
function bersih(v){return Number(String(v||'').replace(/\D/g,''))||0;}function rupiah(n){return Number(n||0).toLocaleString('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0});}
function formatIfMoney(el){if(!el.classList.contains('money-input'))return;let raw=String(el.value||'').trim();let n=bersih(raw);el.value=raw!==''?n.toLocaleString('id-ID'):'';}
function formatTahun(v){v=Number(v||0);if(!isFinite(v)||v<=0)return '0 Tahun';let y=Math.floor(v),m=Math.round((v-y)*12);return y+(m?` Tahun ${m} Bulan`:' Tahun');}
function applyTarget(){const t=TARGETS[targetPendidikan.value];if(!t)return;if(t.usia!=='')usiaMasuk.value=t.usia;if(t.lama!=='')lamaStudi.value=t.lama;}
function getBatas(){const usiaA=Number(usiaAyah.value||0),usiaI=Number(usiaIbu.value||0),pens=Number(usiaPensiun.value||0),usia=Number(usiaAnak.value||0),masuk=Number(usiaMasuk.value||0);const sisaKuliah=masuk-usia;let b=[];if(usiaA&&pens)b.push(pens-usiaA);if(usiaI&&pens)b.push(pens-usiaI);if(sisaKuliah>0)b.push(sisaKuliah);let max=b.length?Math.min(...b):0;return{max,sisaKuliah};}
function updatePeriode(){const prev=periodePersiapan.value;const{max,sisaKuliah}=getBatas();periodePersiapan.innerHTML='';hidePensionWarning();if(!isFinite(max)||max<=0){periodePersiapan.innerHTML='<option value="">Lengkapi data dahulu</option>';periodeInfo.innerText='Isi usia orang tua, usia anak, dan usia masuk pendidikan.';customTahunBox.classList.add('d-none');return;}[3,5,8,10,15,20].forEach(y=>{if(y<=max)periodePersiapan.innerHTML+=`<option value="${y}">${y} Tahun</option>`;});if(sisaKuliah>0&&sisaKuliah<=max)periodePersiapan.innerHTML+=`<option value="kuliah">Sampai Anak Masuk Pendidikan (${formatTahun(sisaKuliah)})</option>`;if(max>=2)periodePersiapan.innerHTML+='<option value="custom">Custom / Tentukan Sendiri</option>';if(!periodePersiapan.innerHTML){let y=Math.max(1,Math.floor(max));periodePersiapan.innerHTML=`<option value="${y}">${y} Tahun</option>`;}if([...periodePersiapan.options].some(o=>o.value===prev))periodePersiapan.value=prev;customTahun.max=Math.floor(max);customTahunBox.classList.toggle('d-none',periodePersiapan.value!=='custom');periodeInfo.innerText=`Periode maksimum yang disarankan: ${formatTahun(max)}, berdasarkan sisa waktu pendidikan dan usia pensiun orang tua.`;}
function showPensionWarning(message){pensionWarning.innerHTML=message;pensionWarning.classList.remove('d-none');}function hidePensionWarning(){pensionWarning.innerHTML='';pensionWarning.classList.add('d-none');}
function getPeriode(){const{max,sisaKuliah}=getBatas();let val=periodePersiapan.value;if(val==='kuliah')return Math.min(sisaKuliah,max);if(val==='custom')return Number(customTahun.value||0);return Math.min(Number(val||0),max);}
function inflasiNum(){return Number(inflasi.value||0)/100;}function rate(){return Number(document.querySelector('input[name="strategiInvestasi"]:checked')?.value||0.04);}function strategiLabel(){let v=rate();return v===0.02?'Konservatif (1–2%)':v===0.06?'Agresif (6% ke atas)':'Moderat (3–5%)';}
function valid(mark=true){let ok=true;document.querySelectorAll('[required]').forEach(el=>{let inv=!String(el.value||'').trim();if(mark)el.classList.toggle('is-invalid',inv);if(inv)ok=false;});if(Number(usiaMasuk.value)<=Number(usiaAnak.value)){if(mark)usiaMasuk.classList.add('is-invalid');ok=false;}if(periodePersiapan.value==='custom'){const{max}=getBatas();const v=Number(customTahun.value||0);if(!v||v<=0||v>max){if(mark){customTahun.classList.add('is-invalid');showPensionWarning(`Periode custom maksimal ${formatTahun(max)}.`);}ok=false;}else{customTahun.classList.remove('is-invalid');hidePensionWarning();}}return ok;}
function data(){let key=targetPendidikan.value;return{namaAyah:namaAyah.value.trim(),usiaAyah:Number(usiaAyah.value),namaIbu:namaIbu.value.trim(),usiaIbu:Number(usiaIbu.value),usiaPensiun:Number(usiaPensiun.value),namaAnak:namaAnak.value.trim(),usiaAnak:Number(usiaAnak.value),targetLabel:TARGETS[key]?.label||'-',usiaMasuk:Number(usiaMasuk.value),lama:Number(lamaStudi.value),biaya:bersih(biayaSaatIni.value),inflasi:inflasiNum(),tahun:Number(tahunSekarang.value),danaAda:bersih(danaAda.value),catatan:catatan.value.trim(),rate:rate(),strategi:strategiLabel(),periode:getPeriode(),sisa:Number(usiaMasuk.value)-Number(usiaAnak.value)}}
function calcSetor(k,p,r){if(k<=0)return 0;let n=Math.round(p*12),m=r/12;if(n<=0)return 0;if(m<=0)return k/n;return k*m/(Math.pow(1+m,n)-1);}
function kosongkan(){resultSection.classList.add('d-none');btnExportPDF.classList.add('d-none');if(donutChart){donutChart.destroy();donutChart=null;}last=null;}
function hitung(mark=true){if(!valid(mark)){if(mark)kosongkan();return;}let d=data();if(d.sisa<=0||d.biaya<=0||d.periode<=0){if(mark)kosongkan();return;}let target=d.biaya*Math.pow(1+d.inflasi,d.sisa);let kurang=Math.max(target-d.danaAda,0);let setor=calcSetor(kurang,d.periode,d.rate);last={...d,target,kurang,setor};renderResult(last);}
function renderResult(d){resultSection.classList.remove('d-none');btnExportPDF.classList.remove('d-none');resultTitle.innerText=`Dana Pendidikan ${d.namaAnak}`;sisaWaktu.innerText=formatTahun(d.sisa);danaDibutuhkan.innerText=rupiah(d.target);sumTarget.innerText=rupiah(d.target);sumDanaAda.innerText=rupiah(d.danaAda);kekuranganDana.innerText=rupiah(d.kurang);setoranBulanan.innerText=rupiah(d.setor);legendDanaAda.innerText=rupiah(d.danaAda);legendKurang.innerText=rupiah(d.kurang);ringkasanText.innerHTML=`Target <strong>${d.targetLabel}</strong> untuk ${d.namaAnak} membutuhkan estimasi dana <strong>${rupiah(d.target)}</strong> dalam ${formatTahun(d.sisa)}. Dana yang sudah ada <strong>${rupiah(d.danaAda)}</strong>, kekurangan dana sekitar <strong>${rupiah(d.kurang)}</strong>.`;renderChart(d);renderReadiness(d);renderInsight(d);renderTimeline(d);}
function renderChart(d){const pct=d.target>0?Math.min(100,(d.danaAda/d.target)*100):0;if(donutChart)donutChart.destroy();donutChart=new Chart(donutChartEl(),{type:'doughnut',data:{labels:['Dana Ada','Kekurangan'],datasets:[{data:[Math.max(d.danaAda,0),Math.max(d.kurang,0)],backgroundColor:['#07355d','#c99b32'],borderWidth:0}]},options:{cutout:'70%',plugins:{legend:{display:false},tooltip:{callbacks:{label:(ctx)=>`${ctx.label}: ${rupiah(ctx.raw)}`}}}}});function donutChartEl(){return document.getElementById('donutChart').getContext('2d');}}
function getReadinessState(d){const items=[{ok:d.target>0,text:'Sudah mengetahui kebutuhan dana'},{ok:d.periode>0,text:'Sudah memiliki target waktu'},{ok:d.setor>=0,text:'Strategi pendanaan sudah disusun'},{ok:d.danaAda>=d.target,text:d.danaAda>=d.target?'Dana awal sudah mencukupi':'Dana awal belum mencukupi'}];const score=items.filter(i=>i.ok).length*25;let msg='Perencanaan baru dimulai, masih banyak aspek yang perlu dipersiapkan.';if(score>=75)msg='Perencanaan sudah baik, fokus pada konsistensi mencapai target.';if(score===100)msg='Perencanaan sangat baik, pertahankan strategi dan evaluasi berkala.';return{score,items,msg};}
function renderReadiness(d){const r=getReadinessState(d);readinessScore.innerText=r.score+'%';readinessBar.style.width=r.score+'%';readinessText.innerText=r.msg;readinessChecklist.innerHTML=r.items.map(i=>`<div class="item ${i.ok?'ok':''}"><i class="bi ${i.ok?'bi-check-circle-fill':'bi-circle'}"></i>${i.text}</div>`).join('');}
function renderInsight(d){let aKul=d.usiaAyah+d.sisa,iKul=d.usiaIbu+d.sisa,aFin=d.usiaAyah+d.periode,iFin=d.usiaIbu+d.periode;insightOrtu.innerHTML=`Saat ${d.namaAnak} masuk ${d.targetLabel}, ${d.namaAyah} diperkirakan berusia <strong>${aKul} tahun</strong> dan ${d.namaIbu} <strong>${iKul} tahun</strong>. Dengan periode persiapan ${formatTahun(d.periode)}, usia saat dana ditargetkan terkumpul: ${d.namaAyah} <strong>${aFin.toFixed(0)} tahun</strong>, ${d.namaIbu} <strong>${iFin.toFixed(0)} tahun</strong>.`;}
function renderTimeline(d){let html='';for(let i=0;i<=d.sisa;i++){let dana=d.biaya*Math.pow(1+d.inflasi,i),naik=((dana-d.biaya)/d.biaya)*100;html+=`<tr><td>${d.tahun+i}</td><td>${d.usiaAnak+i} Tahun</td><td>${rupiah(dana)}</td><td>${naik.toFixed(1)}%</td></tr>`;}tabelDana.innerHTML=html;}
function konsultasiWhatsApp(){if(!last)return;let d=last,msg=`Halo Pak Septino, saya ingin berkonsultasi mengenai hasil simulasi dana pendidikan.\n\nNama Anak: ${d.namaAnak}\nTarget: ${d.targetLabel}\nDana Dibutuhkan: ${rupiah(d.target)}\nDana Saat Ini: ${rupiah(d.danaAda)}\nKekurangan: ${rupiah(d.kurang)}\nSetoran: ${rupiah(d.setor)} / bulan\nPeriode: ${formatTahun(d.periode)}`;window.open(`https://wa.me/${FP.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');}
function konsultasiEmail(){location.href=`mailto:${FP.email}?subject=${encodeURIComponent('Konsultasi Dana Pendidikan')}`;}function konsultasiInstagram(){window.open(FP.instagram,'_blank');}
async function exportPDF(){if(!last){alert('Lengkapi dan hitung data terlebih dahulu.');return;}try{await generateEducationPDF(last,FP);}catch(e){console.error(e);alert('Export PDF gagal: '+(e?.message||e));}}
function resetForm(){simulasiForm.reset();tahunSekarang.value=new Date().getFullYear();document.querySelector('input[name="strategiInvestasi"][value="0.04"]').checked=true;applyTarget();updatePeriode();kosongkan();}
